### ISSUE TITLE
VS2013移植出现错误：error C2039: “min”: 不是“ncnn::std”的成员

### ISSUE THREAD

**Issue by 212152013** [guozhongluo/ncnn-vs2015-examples-demo#1]
1>------ 已启动生成:  项目: ncnn, 配置: Release x64 ------
1>  squeezenet.cpp
1>squeezenet.cpp(62): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据
1>squeezenet.cpp(105): warning C4267: “=”: 从“size_t”转换到“int”，可能丢失数据
1>  input.cpp
1>  mat_pixel.cpp
1>src\mat_pixel.cpp(141): error C2039: “min”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(141): error C2039: “max”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(141): error C3861: “min”:  找不到标识符
1>src\mat_pixel.cpp(141): error C3861: “max”:  找不到标识符
1>src\mat_pixel.cpp(142): error C2039: “min”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(142): error C2039: “max”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(142): error C3861: “min”:  找不到标识符
1>src\mat_pixel.cpp(142): error C3861: “max”:  找不到标识符
1>src\mat_pixel.cpp(143): error C2039: “min”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(143): error C2039: “max”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(143): error C3861: “min”:  找不到标识符
1>src\mat_pixel.cpp(143): error C3861: “max”:  找不到标识符
1>src\mat_pixel.cpp(247): error C2039: “min”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(247): error C2039: “max”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(247): error C3861: “min”:  找不到标识符
1>src\mat_pixel.cpp(247): error C3861: “max”:  找不到标识符
1>src\mat_pixel.cpp(392): error C2039: “min”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(392): error C2039: “max”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(392): error C3861: “min”:  找不到标识符
1>src\mat_pixel.cpp(392): error C3861: “max”:  找不到标识符
1>src\mat_pixel.cpp(393): error C2039: “min”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(393): error C2039: “max”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(393): error C3861: “min”:  找不到标识符
1>src\mat_pixel.cpp(393): error C3861: “max”:  找不到标识符
1>src\mat_pixel.cpp(394): error C2039: “min”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(394): error C2039: “max”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(394): error C3861: “min”:  找不到标识符
1>src\mat_pixel.cpp(394): error C3861: “max”:  找不到标识符
1>src\mat_pixel.cpp(395): error C2039: “min”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(395): error C2039: “max”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(395): error C3861: “min”:  找不到标识符
1>src\mat_pixel.cpp(395): error C3861: “max”:  找不到标识符
1>src\mat_pixel.cpp(525): error C2039: “min”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(525): error C2039: “max”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(525): error C3861: “min”:  找不到标识符
1>src\mat_pixel.cpp(525): error C3861: “max”:  找不到标识符
1>src\mat_pixel.cpp(526): error C2039: “min”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(526): error C2039: “max”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(526): error C3861: “min”:  找不到标识符
1>src\mat_pixel.cpp(526): error C3861: “max”:  找不到标识符
1>src\mat_pixel.cpp(527): error C2039: “min”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(527): error C2039: “max”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(527): error C3861: “min”:  找不到标识符
1>src\mat_pixel.cpp(527): error C3861: “max”:  找不到标识符
1>src\mat_pixel.cpp(621): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
1>src\mat_pixel.cpp(713): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
1>src\mat_pixel.cpp(1120): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
1>src\mat_pixel.cpp(1156): warning C4244: “=”: 从“float”转换到“int”，可能丢失数据
1>src\mat_pixel.cpp(1170): error C2039: “min”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(1170): error C2039: “max”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(1170): error C3861: “min”:  找不到标识符
1>src\mat_pixel.cpp(1170): error C3861: “max”:  找不到标识符
1>src\mat_pixel.cpp(1171): error C2039: “min”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(1171): error C2039: “max”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(1171): error C3861: “min”:  找不到标识符
1>src\mat_pixel.cpp(1171): error C3861: “max”:  找不到标识符
1>src\mat_pixel.cpp(1177): warning C4244: “=”: 从“float”转换到“int”，可能丢失数据
1>src\mat_pixel.cpp(1191): error C2039: “min”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(1191): error C2039: “max”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(1191): error C3861: “min”:  找不到标识符
1>src\mat_pixel.cpp(1191): error C3861: “max”:  找不到标识符
1>src\mat_pixel.cpp(1192): error C2039: “min”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(1192): error C2039: “max”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(1192): error C3861: “min”:  找不到标识符
1>src\mat_pixel.cpp(1192): error C3861: “max”:  找不到标识符
1>src\mat_pixel.cpp(1440): warning C4244: “=”: 从“float”转换到“int”，可能丢失数据
1>src\mat_pixel.cpp(1454): error C2039: “min”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(1454): error C2039: “max”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(1454): error C3861: “min”:  找不到标识符
1>src\mat_pixel.cpp(1454): error C3861: “max”:  找不到标识符
1>src\mat_pixel.cpp(1455): error C2039: “min”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(1455): error C2039: “max”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(1455): error C3861: “min”:  找不到标识符
1>src\mat_pixel.cpp(1455): error C3861: “max”:  找不到标识符
1>src\mat_pixel.cpp(1461): warning C4244: “=”: 从“float”转换到“int”，可能丢失数据
1>src\mat_pixel.cpp(1475): error C2039: “min”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(1475): error C2039: “max”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(1475): error C3861: “min”:  找不到标识符
1>src\mat_pixel.cpp(1475): error C3861: “max”:  找不到标识符
1>src\mat_pixel.cpp(1476): error C2039: “min”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(1476): error C2039: “max”: 不是“ncnn::std”的成员
1>src\mat_pixel.cpp(1476): error C3861: “min”:  找不到标识符
1>src\mat_pixel.cpp(1476): error C3861: “max”:  找不到标识符
1>src\mat_pixel.cpp(1681): warning C4244: “=”: 从“float”转换到“int”，可能丢失数据
1>src\mat_pixel.cpp(1695): error C3861: “min”:  找不到标识符
1>src\mat_pixel.cpp(1695): error C3861: “max”:  找不到标识符
1>src\mat_pixel.cpp(1696): error C3861: “min”:  找不到标识符
1>src\mat_pixel.cpp(1696): error C3861: “max”:  找不到标识符
1>src\mat_pixel.cpp(1702): warning C4244: “=”: 从“float”转换到“int”，可能丢失数据
1>src\mat_pixel.cpp(1716): error C3861: “min”:  找不到标识符
1>src\mat_pixel.cpp(1716): error C3861: “max”:  找不到标识符
1>src\mat_pixel.cpp(1717): error C3861: “min”:  找不到标识符
1>src\mat_pixel.cpp(1717): error C3861: “max”:  找不到标识符
========== 生成:  成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

**Comment by guozhongluo** [comment]
我在头文件添加#include 《algorithm》  就解决min,max函数找不到标识符问题。你试试有效吗？如果无效，百度下应该很好解决这种问题。另外我是用的vs2015，平台差异可能也有影响

**Comment by VivienFu** [comment]
我弄得时候也有这些问题并解决了，你可以参考我的博客记录http://blog.csdn.net/fuwenyan/article/details/76105574

**Comment by 212152013** [comment]
多谢各位热心回复。
