### ISSUE TITLE
找不到 Windows SDK 版本8.1。请安装所需的版本的 Windows SDK 或者在项目属性页中或通过右键单击解决方案并选择“重定解决方案目标”来更改 SDK 版本

### ISSUE THREAD

**Issue by idowe** [guozhongluo/ncnn-vs2015-examples-demo#2]
找不到 Windows SDK 版本8.1。请安装所需的版本的 Windows SDK 或者在项目属性页中或通过右键单击解决方案并选择“重定解决方案目标”来更改 SDK 版本
 使用版本VS2017

**Comment by VivienFu** [comment]
你可以试试这个http://blog.csdn.net/G0m3e/article/details/51508526

**Comment by idowe** [comment]
已解决，是因为没有装
![10d6ccc4-a606-4a5a-966d-e5a162add749](https://user-images.githubusercontent.com/26621270/28625904-26385352-7250-11e7-8124-78f87fc98261.png)
