### ISSUE TITLE
How to use the caffemodel file

### ISSUE THREAD

**Issue by VivienFu** [guozhongluo/ncnn-vs2015-examples-demo#3]
as the example, model loading using:
	squeezenet.load_param("squeezenet_v1.1.param");
	squeezenet.load_model("squeezenet_v1.1.bin");

does ncnn support caffemodel loading? how to load caffemodel?

**Comment by guozhongluo** [comment]
Use the tools file in the ncnn project to translate Caffe model into ncnn model

rely on protobuf library

**Comment by VivienFu** [comment]
@guozhongluo  thanks a lot.  And I found this is very useful too.https://github.com/Tencent/ncnn/wiki/ncnn-%E7%BB%84%E4%BB%B6%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8C%97-alexnet
