### ISSUE TITLE
重新创建工程时，ncnn相关的成员，都提示无法解析的外部符号

### ISSUE THREAD

**Issue by VivienFu** [guozhongluo/ncnn-vs2015-examples-demo#4]
配置后执行楼主的示例，很好用，没有问题了。

可是自己新建了一个工程，工程主文件还是楼主的squeezenet.cpp，工程配置与配置楼主工程时候一样配置的，结果生成项目的时候报错如下（类似错误11个）：
错误	1	error LNK2001: 无法解析的外部符号 "public: int __cdecl ncnn::Extractor::extract(char const *,class ncnn::Mat &)" (?extract@Extractor@ncnn@@QEAAHPEBDAEAVMat@2@@Z)	E:\Algrithm\ncnn\ncnn-vs2015-examples-demo-master\ncnn_faceID\ncnn_faceID.obj	ncnn_faceID

大概会是什么原因呢？

**Comment by guozhongluo** [comment]
你要将用到的.cpp，.h文件添加到工程中编译

**Comment by VivienFu** [comment]
OK，我刚才将你创建工程中的ncnn那个文件夹复制了一份到我的工程中，就好了。谢谢~~！
