### ISSUE TITLE
采用自己的网络模型，计算出的结果与matlab运算出的相差较大

### ISSUE THREAD

**Issue by VivienFu** [guozhongluo/ncnn-vs2015-examples-demo#7]
如题，您可不可以帮忙指点问题可能出在哪儿？

确认过ncnn每层网络输入输出size，简单看了几个FC的weight值，是正确的。

会不会下面的代码有问题？

int detect_faceIDnet(const cv::Mat& bgr, float *feat)
{
ncnn::Mat in = ncnn::Mat::from_pixels(bgr.data, ncnn::Mat::PIXEL_BGR, bgr.cols, bgr.rows);
in.substract_mean_normalize(mean_vals, 0);

ncnn::Extractor ex = faceIDnet.create_extractor();
ex.set_light_mode(true);
ex.set_num_threads(4);
ex.input("data", in);
ncnn::Mat out;
ex.extract("eltwise_fc1", out);
for (int j = 0; j<FEAT_NUM; j++)
{
	const float* prob = out.data + out.cstep * j;
	feat[j] = prob[0];
	//cout << feat[j] << " ";		
}
//cout << endl;
return 0;
}

**Comment by guozhongluo** [comment]
这是MTCNN网络，我最近也打算用ncnn做MTCNN实现。目前你的问题，我还不清楚原因，我们可以交流下，刚好我们都在做MTCNN手机移植。

**Comment by VivienFu** [comment]
后来发现是数据预处理不一致导致的。
处理方式记录在blog中了，http://blog.csdn.net/fuwenyan/article/details/76213015

**Comment by VivienFu** [comment]
@guozhongluo  可以加个QQ交流咩？

**Comment by guozhongluo** [comment]
微信：18317062194
