### ISSUE TITLE
请问模型如何转化

### ISSUE THREAD

**Issue by jhtao1860** [guozhongluo/ncnn-vs2015-examples-demo#8]
自己的.param和.bin如何生成

**Comment by sunbinbin1991** [comment]
[https://github.com/Tencent/ncnn/wiki/ncnn-%E7%BB%84%E4%BB%B6%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8C%97-alexnet](url)
需要自己编译一下就行

**Comment by jhtao1860** [comment]
@sunbinbin1991  多谢
